# SPDX-FileCopyrightText: Copyright 2025 Dash0 Inc.
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dash0-operator-nodejs-20-express-test-deployment
  labels:
    app: {{ .Values.deployment.selector }}
    {{- with .Values.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.selector }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.selector }}
        test.label/key: "label-value"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.deployment.targetPort }}"
        test.annotation/key: "annotation value"
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: PORT
              value: "{{ .Values.deployment.targetPort }}"
            # - name: CREATE_TARGET_INFO_METRIC
            #   value: "true"
          ports:
            - containerPort: {{ .Values.deployment.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.deployment.targetPort }}
            initialDelaySeconds: 1
            periodSeconds: 1
          # For testing k8s.volume.* metrics with a volume:
          # volumeMounts:
          # - name: test-volume
          #   mountPath: /etc/test-volume
          #   readOnly: false
      # For testing k8s.volume.* metrics with a hostPath volume:
      # volumes:
      # -  name: test-volume
      #    hostPath:
      #      path: /data/dash0-operator/test
      #      type: DirectoryOrCreate
      #
      # For testing k8s.volume.* metrics with a PVC volume, requires to execute
      #     kubectl apply -f test-resources/node.js/express/test-pvc.yaml
      # before deploying. Looks like metrics for PVC-based volumes are currently not collected?
      # volumes:
      # - name: test-volume
      #   persistentVolumeClaim:
      #     claimName: test-pvc-volume
{{- end }}
