# SPDX-FileCopyrightText: Copyright 2025 Dash0 Inc.
# SPDX-License-Identifier: Apache-2.0

operator:
  targetAllocator:
    mTls:
      enabled: true
      serverCertSecretName: "ta-server-cert-secret"
      clientCertSecretName: "ta-client-cert-secret"
