apiVersion: operator.dash0.com/v1alpha1
kind: Dash0OperatorConfiguration
metadata:
  name: dash0-operator-configuration-resource
spec:
  export:
    dash0:
      endpoint: ingress.eu-west-1.aws.dash0-dev.com:4317
      authorization:
        secretRef:
          name: dash0-authorization-secret
          key: token
      apiEndpoint: https://api.eu-west-1.aws.dash0-dev.com
